Remove legacy feature #(set-time-signature)
In lilypond 2.16.2, the line provokes
   error: GUILE signaled an error for the expression beginning here
It's no longer clear to me what it's supposed to achieve, and it seems
to set (the last 4 bars) fine without it.